### ISSUE TITLE
GeoNode Geoserver has an invalid generic style

### ISSUE THREAD

**Issue by kikislater** [GeoNode/data-docker#8]
May be better to link it here : 
https://github.com/GeoNode/geonode/issues/9564

**Comment by afabiani** [comment]
I confirm the `generic.sld` file is empty inside the `default` GeoNode-GeoServer `DATADIR`

![image](https://user-images.githubusercontent.com/1278021/177140479-ce73e014-5d7e-4c43-9ae8-f2acd290310b.png)

**Comment by giohappy** [comment]
Created upstream issue https://github.com/GeoNode/geoserver-geonode-ext/issues/124
